#!/usr/bin/env node
/**
 * Merge canonicalization metadata into catalog/catalog.json.
 * Input is an array of role/skill metadata; equal names replace previous entries.
 * Validate the entire catalog before writing because generated scopes depend on it.
 *
 * node bootstrap/merge-catalog.mjs --from metadata.json [--dry-run]
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const KIT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CAT = path.join(KIT, "catalog", "catalog.json");
const TIERS = new Set(["none", "git-read", "check-runner", "docs-ops", "dev", "lead", "custom"]);
const REG = JSON.parse(fs.readFileSync(path.join(KIT, "catalog", "placeholders.json"), "utf8"));

function args(argv) {
  const o = { from: "", dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--from") o.from = argv[++i];
    else if (argv[i] === "--dry-run") o.dryRun = true;
  }
  return o;
}

function base() {
  if (fs.existsSync(CAT)) return JSON.parse(fs.readFileSync(CAT, "utf8"));
  return {
    $comment: "GENERATED by bootstrap/merge-catalog.mjs. Tracks are maintained in catalog/tracks.json; roles/skills come from canonicalization metadata. Files in catalog/agents and catalog/skills provide the content; this JSON is the index and default scopes. Used by bootstrap/new-project.mjs and bootstrap/gap-report.mjs.",
    version: 1,
    core: {},
    tracks: {},
    agents: {},
    skills: {},
  };
}

/** tracks.json is the source of track definitions; catalog.json embeds the derived index. */
function dobrarTrilhas(cat) {
  const p = path.join(KIT, "catalog", "tracks.json");
  if (!fs.existsSync(p)) return 0;
  const t = JSON.parse(fs.readFileSync(p, "utf8"));
  cat.core = t.core || {};
  cat.tracks = t.tracks || {};
  return Object.keys(cat.tracks).length;
}

/** Scope matching supports directory prefixes, trailing stem wildcards, and exact
 * files. Normalize unsupported glob syntax at the boundary instead of silently
 * generating an allow entry that never matches. */
const truncados = [];
const descartados = [];

/** Metadata may mix paths with comments, shell restrictions, or unsupported
 * globs. Recover path-plus-comment entries, but reject prose and shell commands
 * rather than silently treating their first word as an allowed filename. */
function normalizarCaminho(p, dono) {
  const bruto = String(p).trim().replace(/\\/g, "/");
  let s = bruto.split(/[\s,]/)[0];

  const pareceCaminho = /^[<>A-Za-z0-9_@.\-][<>A-Za-z0-9_@.\-/*]*$/.test(s)
    && (s.includes("/") || s.includes(".") || s.includes("<"))
    && !s.startsWith("*");
  if (!pareceCaminho) { descartados.push(`${dono}: '${bruto}'`); return null; }
  if (s !== bruto) truncados.push(`${dono}: '${bruto}' -> '${s}'`);

  s = s.replace(/^\*\*\//, "");        // **/Binaries/** -> Binaries/**
  s = s.replace(/\/\*\*\//g, "/");     // a/**/b         -> a/b
  s = s.replace(/\/\*\*\/?$/, "/");    // src/routes/**  -> src/routes/
  s = s.replace(/\/\*$/, "/");         // src/routes/*   -> src/routes/

  // Only a trailing stem wildcard is supported. Reject other wildcards rather than leaving inert permissions.
  if (s.includes("*") && !/^[^*]+\*$/.test(s)) { descartados.push(`${dono}: '${bruto}' (wildcard inside path)`); return null; }
  return s;
}

/** Restore placeholder names when the harness HTML-escapes angle brackets. */
function normalizarPlaceholder(p) {
  return String(p).replace(/&lt;|&gt;|[<>]/g, "").trim();
}

function validar(cat) {
  const erros = [];
  const skillsConhecidas = new Set(Object.keys(cat.skills));
  for (const [n, d] of Object.entries(cat.agents)) {
    if (!fs.existsSync(path.join(KIT, "catalog", "agents", `${n}.md`))) erros.push(`agent '${n}' is indexed but missing catalog/agents/${n}.md`);
    if (!TIERS.has(d.shell || "none")) erros.push(`agent '${n}': unknown shell tier '${d.shell}'`);
    if (d.read_only && (d.write || []).length) erros.push(`agent '${n}': read_only with write entries`);
    if (!d.read_only && !(d.write || []).length) erros.push(`agent '${n}': writable role has no allowed paths; resolve this`);
    // Reject remaining unsupported globs after normalization.
    for (const p of [...(d.write || []), ...(d.deny || [])]) {
      if (p.includes("*") && !/^[^*]+\*$/.test(p)) erros.push(`agent '${n}': path '${p}' uses unsupported glob syntax (only 'dir/' or 'stem*')`);
    }
    for (const s of d.needs_skills || []) if (!skillsConhecidas.has(s)) erros.push(`agent '${n}' requires skill '${s}', which is missing from the catalog`);
  }
  for (const n of Object.keys(cat.skills)) {
    if (!fs.existsSync(path.join(KIT, "catalog", "skills", n, "SKILL.md"))) erros.push(`skill '${n}' is indexed but missing catalog/skills/${n}/SKILL.md`);
  }
  for (const [t, d] of Object.entries(cat.tracks)) {
    for (const a of d.agents || []) if (!cat.agents[a]) erros.push(`track '${t}' lists agent '${a}', which is missing from the catalog`);
    for (const s of d.skills || []) if (!cat.skills[s]) erros.push(`track '${t}' lists skill '${s}', which is missing from the catalog`);
    // Optional interview choices must reference real catalog entries.
    for (const [cond, nomes] of Object.entries(d.condicionais || {})) {
      for (const n of nomes) if (!cat.agents[n] && !cat.skills[n]) erros.push(`track '${t}', condition '${cond}': '${n}' is missing from the catalog`);
    }
  }
  for (const [n, por] of Object.entries(cat.core?.opcionais || {})) {
    if (!cat.agents[n] && !cat.skills[n]) erros.push(`core.opcionais lists '${n}' (${String(por).slice(0, 40)}...), which is missing from the catalog`);
  }
  // Declared and actual placeholders must agree so generation replaces every required value.
  for (const [tipo, dir] of [["agents", "agents"], ["skills", "skills"]]) {
    for (const [n, d] of Object.entries(cat[tipo])) {
      const p = tipo === "agents" ? path.join(KIT, "catalog", dir, `${n}.md`) : path.join(KIT, "catalog", dir, n, "SKILL.md");
      if (!fs.existsSync(p)) continue;
      const txt = fs.readFileSync(p, "utf8");
      // Derive placeholders from source text and paths. Exclude the literal explanatory word PLACEHOLDER.
      const doTexto = (txt.match(/<[A-Z][A-Z0-9_]+>/g) || []).map((s) => s.slice(1, -1));
      const dosCaminhos = [...(d.write || []), ...(d.deny || [])].flatMap((p) => (p.match(/<[A-Z][A-Z0-9_]+>/g) || []).map((s) => s.slice(1, -1)));
      d.placeholders = [...new Set([...doTexto, ...dosCaminhos].filter((s) => s !== "PLACEHOLDER"))].sort();

      // Derive required skills and model from the current agent frontmatter —
      // never trust a canonization-run metadata blob, which goes stale the
      // moment a hand-edit (e.g. a model swap) touches the file directly and
      // no one reruns the merge. Found by an external audit (2026-09-17):
      // catalog.json said "fable" for four agents whose files already said
      // "opus", because the earlier fable->opus fix only touched the files.
      if (tipo === "agents") {
        const fm = txt.split("---")[1] || "";
        const modelMatch = fm.match(/^model:\s*(\S+)/m);
        if (modelMatch) d.model = modelMatch[1];
        const m = fm.match(/skills:([\s\S]*?)(?:\n[a-z_]+:|$)/);
        const pedidas = m
          ? m[1].split(/[\n,·]/).map((x) => x.replace(/^\s*-\s*/, "").trim()).filter((x) => x && !x.startsWith("<"))
          : [];
        const fica = pedidas.filter((s) => skillsConhecidas.has(s));
        for (const s of pedidas) if (!skillsConhecidas.has(s)) erros.push(`agents/${n}: frontmatter requires skill '${s}', which is missing from the catalog`);
        if (fica.length) d.needs_skills = [...new Set(fica)].sort(); else delete d.needs_skills;
      }
    }
  }
  return erros;
}

function main() {
  const o = args(process.argv.slice(2));
  if (!o.from) { console.error("usage: --from <file.json> [--dry-run]"); process.exit(2); }
  const entrada = JSON.parse(fs.readFileSync(path.resolve(o.from), "utf8"));
  const itens = Array.isArray(entrada) ? entrada : (entrada.canonizados || entrada.items || []);
  if (!itens.length) { console.error("input contains no items"); process.exit(2); }

  const cat = base();
  let novos = 0, subst = 0;
  for (const m of itens) {
    if (!m?.name || !m?.kind) continue;
    const destino = m.kind === "agent" ? cat.agents : cat.skills;
    if (destino[m.name]) subst++; else novos++;
    // Scope rationales enter generated projects. Keep them short and exclude source-project references.
    const FROTA = /thaydom|codejtech|chronoguard|sprout-academy|vice-addict|bastiao|caderneta|wash-pricer|one-more-arrow|one-move|distrito-de-cinzas|vigilia|coroa-de-fronteira|toybox|site-forge|super-racer|fresh-start|academy-agent|stable-dynasty|luizaofoot|\bfood\b/i;
    let why = String(m.why || "").split(/(?<=\.)\s/)[0].trim();
    if (why.length > 240 || FROTA.test(why)) why = m.purpose || "";
    if (why.length > 240) why = why.slice(0, 237) + "...";

    const e = {
      purpose: m.purpose || "",
      tracks: m.tracks?.length ? m.tracks : ["*"],
      placeholders: [],
      why,
    };
    if (m.kind === "agent") {
      e.model = m.model || "sonnet";
      e.shell = m.shell || "none";
      e.read_only = !!m.read_only;
      // Normalize placeholder aliases inside paths as well as prose.
      const aplicarRegistro = (p) => {
        let s = p;
        for (const [de, para] of Object.entries(REG.apelidos || {})) s = s.split(`<${de}>`).join(`<${para}>`);
        for (const [de, para] of Object.entries(REG.resolvidos || {})) if (de !== "$comment") s = s.split(`<${de}>`).join(para);
        return s;
      };
      e.write = [...new Set((m.write || []).map((p) => normalizarCaminho(aplicarRegistro(p), m.name)).filter(Boolean))];
      const deny = [...new Set((m.deny || []).map((p) => normalizarCaminho(aplicarRegistro(p), m.name)).filter(Boolean))];
      if (deny.length) e.deny = deny;
      if (m.needs_skills?.length) e.needs_skills = m.needs_skills;
    }
    destino[m.name] = e;
  }

  // Report and prune references to skills that are not present in the catalog.
  const conhecidas = new Set(Object.keys(cat.skills));
  const podadas = [];
  for (const [n, d] of Object.entries(cat.agents)) {
    if (!d.needs_skills) continue;
    const fica = d.needs_skills.filter((s) => conhecidas.has(s));
    for (const s of d.needs_skills) if (!conhecidas.has(s)) podadas.push(`${n} -> ${s}`);
    if (fica.length) d.needs_skills = fica; else delete d.needs_skills;
  }
  if (truncados.length) {
    console.log(`${truncados.length} path(s) truncated (comment appended to path):`);
    for (const t of truncados.slice(0, 12)) console.log(`  ${t}`);
    if (truncados.length > 12) console.log(`  ... +${truncados.length - 12}`);
  }
  if (descartados.length) {
    console.log(`${descartados.length} non-path entries DISCARDED (usually shell restrictions placed in the wrong list; shell tiers cover them):`);
    for (const d of descartados.slice(0, 12)) console.log(`  ${d}`);
    if (descartados.length > 12) console.log(`  ... +${descartados.length - 12}`);
  }
  if (podadas.length) {
    console.log(`${podadas.length} needs_skills entries pruned because they are missing from the catalog:`);
    for (const p of podadas) console.log(`  ${p}`);
  }

  const nTrilhas = dobrarTrilhas(cat);
  const erros = validar(cat);
  if (erros.length) {
    console.error(`${erros.length} problem(s); NOTHING was written:`);
    for (const e of erros) console.error(`  ${e}`);
    process.exit(1);
  }
  if (o.dryRun) { console.log(`[dry-run] ok: ${novos} new, ${subst} replaced, ${nTrilhas} track(s); validation passed`); return; }
  fs.mkdirSync(path.dirname(CAT), { recursive: true });
  fs.writeFileSync(CAT, JSON.stringify(cat, null, 2) + "\n");
  console.log(`catalog.json: ${novos} new, ${subst} replaced — ${Object.keys(cat.agents).length } agents, ${Object.keys(cat.skills).length} skills, ${nTrilhas } tracks; validation passed`);
}

main();
